#! /bin/bash
export JACOPYAN_ROOT='/home/vrath/JacoPyAn/'
export JACOPYAN_DATA='/home/vrath/work/MT_Data/'

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/home/vrath/.Miniconda/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
__conda_setup="$('${MY_CONDA_ROOT}/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f ${MY_CONDA_ROOT}/etc/profile.d/conda.sh ]; then
        . ${MY_CONDA_ROOT}/etc/profile.d/conda.sh
    else
        export PATH='${MY_CONDA_ROOT}/bin:$PATH'
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

echo "Bash version ${BASH_VERSION}..."
mamba update --all -n base
conda  activate JacoPyAn
mamba update --all -y -n JacoPyAn
mamba env export -n JacoPyAn > ${JACOPYAN_ROOT}/environment/JacoPyAn.yml
mamba list -n JacoPyAn > ${JACOPYAN_ROOT}/environment/JacoPyAn.txt






